name       : ffmpeg-chromium-opera
version    : 112.0.5615.165
release    : 11
source     :
    - https://commondatastorage.googleapis.com/chromium-browser-official/chromium-112.0.5615.165.tar.xz : 168c62fea9f428f99fbf967f36a75ee5da160429e3a5b86bf02188c5fe7c79fd
license    :
    - BSD-3-Clause
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : multimedia.codecs
summary    : Chromium's ffmpeg for opera-stable.
description: |
    Chromium's ffmpeg for opera-stable with support for proprietary codecs such as H.264 enabled.
clang      : yes
libsplit   : no
networking : yes
optimize   : no-symbolic
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libdrm)
    - pkgconfig(libevdev)
    - pkgconfig(libjpeg)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(libxslt)
    - pkgconfig(nss)
    - pkgconfig(xtst)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
    - nodejs
environment: |
    unset LD_AS_NEEDED
setup      : |
    FLAGS=(`cat $pkgfiles/gn-build-config`)

    # Misc
    %patch -Np0 < $pkgfiles/angle-wayland-include-protocol.patch

    # Bootstrap GN with build config
    python3 tools/clang/scripts/update.py
    python3 tools/gn/bootstrap/bootstrap.py --gn-gen-args "${FLAGS[*]}"

    # Fix missing tools
    mkdir -p third_party/node/linux/node-linux-x64/bin
    ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/
build      : |
    ninja -C out/Release media/ffmpeg -v
install    : |
    install -Dm00644 out/Release/libffmpeg.so $installdir/usr/lib/opera/libffmpeg.so
